# Generated by Django 4.1.4 on 2022-12-29 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_count', models.BigIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Sahə, m² ilə göstərilmişdir', max_digits=10, null=True)),
                ('area_of_land', models.DecimalField(blank=True, decimal_places=2, help_text='Torpaq sahəsi, sot ilə göstərilmişdir', max_digits=10, null=True)),
                ('name', models.CharField(help_text='Url ending', max_length=50)),
                ('full_cost', models.DecimalField(blank=True, decimal_places=2, help_text='AZN', max_digits=10, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='AZN/m²', max_digits=10, null=True)),
                ('location_width', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude', max_digits=10, null=True)),
                ('location_height', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude', max_digits=10, null=True)),
                ('type', models.BigIntegerField(choices=[(1, 'monthly rent'), (2, 'daily rent'), (3, 'sale'), (10, '##BUG##')])),
                ('have_government_deed', models.BooleanField(blank=True, null=True)),
                ('have_mortgage_support', models.BooleanField(blank=True, null=True)),
                ('building_stage_height', models.BigIntegerField(blank=True, null=True)),
                ('stage', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('advertisement_create_date', models.DateTimeField(blank=True, null=True)),
                ('advertisement_expire_date', models.DateTimeField(blank=True, null=True)),
                ('advertisement_deleted_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('building_type', models.BigIntegerField(choices=[(1, 'flat old constructed'), (2, 'flat new constructed'), (3, 'home / villa'), (4, 'garden'), (5, 'office'), (6, 'garage'), (7, 'object building'), (8, 'land'), (9, 'another'), (10, '##BUG##')])),
                ('admin_confirmation_status', models.BigIntegerField(blank=True, choices=[(1, 'initial'), (2, 'admin confirm'), (3, 'expired'), (4, 'other'), (10, '##BUG##')], null=True)),
                ('advertisement_type', models.BigIntegerField(choices=[(1, 'normal'), (2, 'upper'), (3, 'vip'), (4, 'premium'), (10, '##BUG##')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
