# Generated by Django 4.1.4 on 2022-12-29 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_count', models.BigIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_of_land', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('full_cost', models.DecimalField(blank=True, decimal_places=2, help_text='AZN', max_digits=10, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='AZN/m²', max_digits=10, null=True)),
                ('location_width', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude', max_digits=10, null=True)),
                ('location_height', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude', max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
